export type {
    WidgetCategory,
    WidgetDef,
    WidgetInstance,
} from '../../../home/widgets/widgetRegistry';

export const EMPRESA_WIDGET_REGISTRY: import('../../../home/widgets/widgetRegistry').WidgetDef[] = [
    {
        id: 'kpi-strip',
        label: 'KPI Strip',
        description: 'Recomendaciones ML, favoritos, visitas y servicios activos de tu empresa.',
        iconName: 'Gauge',
        defaultColSpan: 4,
        defaultRowSpan: 1,
        minColSpan: 4,
        maxColSpan: 4,
        minRowSpan: 1,
        maxRowSpan: 1,
        category: 'analytics',
    },
    {
        id: 'engagement-trend',
        label: 'Tendencia de engagement',
        description: 'Interacciones diarias de los ultimos 30 dias con tus servicios.',
        iconName: 'LineChart',
        defaultColSpan: 2,
        defaultRowSpan: 2,
        minColSpan: 2,
        maxColSpan: 4,
        minRowSpan: 2,
        maxRowSpan: 3,
        category: 'analytics',
    },
    {
        id: 'top-services',
        label: 'Top servicios',
        description: 'Ranking de servicios con mayor engagement y calificación.',
        iconName: 'Star',
        defaultColSpan: 1,
        defaultRowSpan: 2,
        minColSpan: 1,
        maxColSpan: 2,
        minRowSpan: 2,
        maxRowSpan: 3,
        category: 'analytics',
    },
    {
        id: 'company-profile',
        label: 'Datos de la empresa',
        description: 'Información registrada de tu perfil empresarial.',
        iconName: 'Building2',
        defaultColSpan: 1,
        defaultRowSpan: 2,
        minColSpan: 1,
        maxColSpan: 2,
        minRowSpan: 2,
        maxRowSpan: 3,
        category: 'operations',
    },
    {
        id: 'quick-actions',
        label: 'Accesos rapidos',
        description: 'Enlaces directos a servicios, analytics y perfil.',
        iconName: 'Activity',
        defaultColSpan: 2,
        defaultRowSpan: 1,
        minColSpan: 2,
        maxColSpan: 4,
        minRowSpan: 1,
        maxRowSpan: 2,
        category: 'operations',
    },
    {
        id: 'quality-score',
        label: 'Evaluación SMARTUR',
        description: 'Puntaje de calidad asignado por el equipo SMARTUR.',
        iconName: 'Award',
        defaultColSpan: 2,
        defaultRowSpan: 1,
        minColSpan: 1,
        maxColSpan: 4,
        minRowSpan: 1,
        maxRowSpan: 2,
        category: 'analytics',
    },
    {
        id: 'status-banner',
        label: 'Estado de revision',
        description: 'Aviso visible mientras tu empresa esta en revision.',
        iconName: 'AlertCircle',
        defaultColSpan: 4,
        defaultRowSpan: 1,
        minColSpan: 2,
        maxColSpan: 4,
        minRowSpan: 1,
        maxRowSpan: 1,
        category: 'operations',
    },
    {
        id: 'lang-switch',
        label: 'Idioma & Tema',
        description: 'Cambia el idioma de la interfaz y el tema visual.',
        iconName: 'Globe2',
        defaultColSpan: 1,
        defaultRowSpan: 1,
        minColSpan: 1,
        maxColSpan: 2,
        minRowSpan: 1,
        maxRowSpan: 1,
        category: 'tools',
    },
];

export const EMPRESA_WIDGET_REGISTRY_MAP: Record<string, import('../../../home/widgets/widgetRegistry').WidgetDef> =
    Object.fromEntries(EMPRESA_WIDGET_REGISTRY.map((w) => [w.id, w]));

export const DEFAULT_EMPRESA_WIDGET_INSTANCES: import('../../../home/widgets/widgetRegistry').WidgetInstance[] = [
    { id: 'inst-kpi-strip', widgetId: 'kpi-strip', colSpan: 4, rowSpan: 1 },
    { id: 'inst-engagement-trend', widgetId: 'engagement-trend', colSpan: 2, rowSpan: 2 },
    { id: 'inst-top-services', widgetId: 'top-services', colSpan: 1, rowSpan: 2 },
    { id: 'inst-company-profile', widgetId: 'company-profile', colSpan: 1, rowSpan: 2 },
    { id: 'inst-quick-actions', widgetId: 'quick-actions', colSpan: 2, rowSpan: 1 },
    { id: 'inst-quality-score', widgetId: 'quality-score', colSpan: 2, rowSpan: 1 },
];
